Add test cases for ShoppingCart entity
vitaliiplys/online-bookstore pull request #13
Opened 2024-03-02 15:48 UTC by vitaliiplys

<img width="1440" alt="Снимок экрана 2024-03-02 в 17 46 35" src="https://github.com/vitaliiplys/online-bookstore/assets/125730891/2eafa00d-e69c-496f-aefa-7f22a6beb6cb">

2024-03-02 16:27 UTC, olekskov requested changes

2024-03-02 16:27 UTC, olekskov commented on src/test/java/com/example/onlinebookstore/controller/ShoppingCartControllerTest.java
> +    }
Please also check by means of repository that DB state was changed as expected (cartItem was created in DB)

2024-03-02 16:27 UTC, olekskov commented on src/test/java/com/example/onlinebookstore/controller/ShoppingCartControllerTest.java
> +    }
same here, need to check that quantity was updated in DB

2024-03-02 16:27 UTC, olekskov commented on src/test/java/com/example/onlinebookstore/controller/ShoppingCartControllerTest.java
> +        Assertions.assertTrue(result.getResponse().getContentAsString().isEmpty());
same here

2024-03-05 17:28 UTC, Vasul-Pankiv approved these changes

2024-03-06 16:06 UTC, merged